### ISSUE TITLE
Cannot get Item charge for null or AIR

### ISSUE THREAD

**Issue by Broascaa** [NCBPFluffyBear/FluffyMachines#134]
## Description (Required)
Well, it's very simple.. This error keep spam in my console!!!!

## Steps to reproduce the Issue (Required)
I don't know exactly.. Just watch the photo, this bug appeard from nowhere..

## Expected behavior (Required)
-

## Server Log / Error Report
[13:31:11] [Server thread/WARN]: [FluffyMachines] Task #22923247 for FluffyMachines vDEV - 130 (git 01c839cc) generated an exception
java.lang.IllegalArgumentException: Cannot get Item charge for null or AIR
	at io.github.thebusybiscuit.slimefun4.core.attributes.Rechargeable.getItemCharge(Rechargeable.java:75) ~[Slimefun4 - DEV 1039 (git 3ae41).jar:?]
	at io.ncbpfluffybear.fluffymachines.items.tools.PortableCharger$1.run(PortableCharger.java:110) ~[Slimefun - FluffyMachines - DEV 129 (git e781c).jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[13:31:12] [Server thread/WARN]: [FluffyMachines] Task #22923247 for FluffyMachines vDEV - 130 (git 01c839cc) generated an exception
java.lang.IllegalArgumentException: Cannot get Item charge for null or AIR
	at io.github.thebusybiscuit.slimefun4.core.attributes.Rechargeable.getItemCharge(Rechargeable.java:75) ~[Slimefun4 - DEV 1039 (git 3ae41).jar:?]
	at io.ncbpfluffybear.fluffymachines.items.tools.PortableCharger$1.run(PortableCharger.java:110) ~[Slimefun - FluffyMachines - DEV 129 (git e781c).jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

## Environment (Required)
![image](https://user-images.githubusercontent.com/86567732/221369291-1ce8afe0-8df3-4ddb-ae67-7e3149a0f8e9.png)

 - Minecraft Version: 1.19.2
 - CS-CoreLib Version: attached in photo
 - Slimefun Version: attached in photo
 - FluffyMachines Version:  attached in photo

**Comment by NCBPFluffyBear** [comment]
This has been reported on discord too, but I unfortunately can't reproduce. The error doesn't really tell me much, unless I know the scenario where this happened. If you have any additional information, please follow up later. I'll leave this open in the meantime.
