### ISSUE TITLE
Fluffy Machine No longer loads

### ISSUE THREAD

**Issue by SomethingBasic01** [NCBPFluffyBear/FluffyMachines#141]
The plugin worked perfectly for weeks, then today for some reason after a restart the plugin no longer loads and gets disabled at startup automatically for some reason. 

## Steps to reproduce the Issue (Required)
(server is 1.19.4)
1.)Launch server
2.)Restart?

## Expected behavior (Required)
For the plugin to load normally

## Server Log / Error Report
[00:33:31] [Server thread/INFO]: [FluffyMachines] Enabling FluffyMachines vDEV - 130 (git 01c839cc)
[00:33:31] [Server thread/ERROR]: Error occurred while enabling FluffyMachines vDEV - 130 (git 01c839cc) (Is it up to date?)
java.lang.IllegalArgumentException: Recipe must have non-AIR result.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:61) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:20) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:24) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.world.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:63) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.world.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at org.bukkit.craftbukkit.v1_19_R3.inventory.RecipeIterator.next(RecipeIterator.java:41) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at org.bukkit.craftbukkit.v1_19_R3.inventory.RecipeIterator.next(RecipeIterator.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at io.ncbpfluffybear.fluffymachines.FluffyMachines.onEnable(FluffyMachines.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

## Environment (Required)
![image](https://github.com/NCBPFluffyBear/FluffyMachines/assets/144187313/8993f2d1-7d9f-4c71-b9e8-34b066639ade)
![image](https://github.com/NCBPFluffyBear/FluffyMachines/assets/144187313/b264ae5a-be0b-46db-92b9-a998944b80be)

**Comment by NCBPFluffyBear** [comment]
Does this issue still occur? Are there custom recipes (using the vanilla crafting table) being used on your server?

**Comment by NCBPFluffyBear** [comment]
Closing due to inactivity.
