### ISSUE TITLE
Not loading on Purpur 1.20.4

### ISSUE THREAD

**Issue by anthonykour** [NCBPFluffyBear/FluffyMachines#147]
## Description:
Updated my Purpur server from 1.20.2 to 1.20.4 and the FluffyMachines plugin gave me an error about the plugin not being up-to-date.

## Steps to reproduce the Issue:
Stop server
Change server version from Purpur 1.20.2 to Purpur 1.20.4
Restart server

## Expected behavior:
Load the plugin as intended, as the changes from MC Version 1.20.2 --> 1.20.4 are not that drastic, only grass was changed.
From "Grass" to "Short_Grass".

## Server Log / Error Report:
`[17:28:04 INFO]: [FluffyMachines] Enabling FluffyMachines vDEV - 132 (git ccf029ba)
[17:28:04 ERROR]: Error occurred while enabling FluffyMachines vDEV - 132 (git ccf029ba) (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.enchantments.Enchantment.isAcceptingRegistrations()'
        at io.ncbpfluffybear.fluffymachines.FluffyMachines.onEnable(FluffyMachines.java:61) ~[FluffyMachines - DEV 132 (git ccf02).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2112]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[17:28:04 INFO]: [FluffyMachines] Disabling FluffyMachines vDEV - 132 (git ccf029ba)`

## Environment:
Purpur 1.20.4 Build 2112

 - Minecraft Version: 1.20.4
 - CS-CoreLib Version: N/A
 - Slimefun Version: SlimeFun4 Build 1118
 - FluffyMachines Version: Dev 132

**Comment by NCBPFluffyBear** [comment]
Hello, thanks for reporting!

I'm aware of this issue right now, but am unable to fix it right now since the issue seems from the new Bukkit API. I'll look into some workarounds in the meantime.

**Comment by anthonykour** [comment]
My main concern is for my water sprinklers, they were keeping my crops watered for me. Would there be a way to make those work again?

**Comment by kylemarham** [comment]
+1, we need fluffymachines fixed as it is an integral part of Slimefun!

**Comment by NCBPFluffyBear** [comment]
> My main concern is for my water sprinklers, they were keeping my crops watered for me. Would there be a way to make those work again? 

The errors are from loading the Glow enchant, which is what makes the portable chargers Glow. It's possible to just get rid of the Glow entirely and restore the plugin, if that is something you are fine with.

**Comment by anthonykour** [comment]
> > My main concern is for my water sprinklers, they were keeping my crops watered for me. Would there be a way to make those work again?
> 
> The errors are from loading the Glow enchant, which is what makes the portable chargers Glow. It's possible to just get rid of the Glow entirely and restore the plugin, if that is something you are fine with.

I personally don't use the portable chargers, so I would be okay with that feature being gone, if it means the plugin would work again.

**Comment by kylemarham** [comment]
Likewise, happy to accept some features of the addon not working if most others do.

**Comment by NCBPFluffyBear** [comment]
Implemented a workaround, build is on https://blob.build/project/FluffyMachines. Please let me know if there are any other issues, and close this issue if it works :)

**Comment by anthonykour** [comment]
Other than the warning that shows now that the enchantment has failed to register, the plugin seems to be working as expected. Thank you!

**Comment by NCBPFluffyBear** [comment]
> Other than the warning that shows now that the enchantment has failed to register, the plugin seems to be working as expected. Thank you!

Could you send a screenshot of the error (or send a pastebin link)?

**Comment by anthonykour** [comment]
> > Other than the warning that shows now that the enchantment has failed to register, the plugin seems to be working as expected. Thank you!
> 
> Could you send a screenshot of the error (or send a pastebin link)?

![Uploading Screenshot_20240102-145858.png…]()

**Comment by anthonykour** [comment]
![Screenshot_20240102-145858](https://github.com/NCBPFluffyBear/FluffyMachines/assets/28590639/31840417-a183-49d7-860f-c68c2bdf0813)

**Comment by NCBPFluffyBear** [comment]
Just fixed auto updating, I suggest you manually update to the newest build

**Comment by anthonykour** [comment]
Loaded up the lastest build with zero errors, thanks again!
