### ISSUE TITLE
Latest SF update breaks CargoManipulator

### ISSUE THREAD

**Issue by IAISI** [NCBPFluffyBear/FluffyMachines#149]
## Description (Required)

https://github.com/NCBPFluffyBear/FluffyMachines/blob/8f6bb4f53a9503df27a749c5a18d19efced3c78f/src/main/java/io/ncbpfluffybear/fluffymachines/items/tools/CargoManipulator.java#L14
is broken by 
https://github.com/Slimefun/Slimefun4/commit/b841828454168bbdbb211a9aa41d9ab244389c60

## Steps to reproduce the Issue (Required)

Use CargoManipulator with latest build of SF

## Server Log / Error Report

```
com.destroystokyo.paper.exception.ServerEventException: Could not pass event PlayerInteractEvent to FluffyMachines v1.0.0
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:72)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:536)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1935)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
	at net.minecraft.network.protocol.PlayerConnectionUtils.a(PlayerConnectionUtils.java:54)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1464)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:195)
	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1441)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1364)
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1224)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoClassDefFoundError: io/github/thebusybiscuit/slimefun4/libraries/unirest/json/JSONObject
	at SlimefunFluffyMachines.jar//io.ncbpfluffybear.fluffymachines.items.tools.CargoManipulator.copyNode(CargoManipulator.java:106)
	at SlimefunFluffyMachines.jar//io.ncbpfluffybear.fluffymachines.items.tools.CargoManipulator.onCargoManipulatorUse(CargoManipulator.java:93)
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1935)
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37)
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1464)
	at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:195)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1441)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1364)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224)
	... 2 more
Caused by: java.lang.ClassNotFoundException: io.github.thebusybiscuit.slimefun4.libraries.unirest.json.JSONObject
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 27 more
```

## Environment (Required)

 - Minecraft Version: 1.20.4
 - CS-CoreLib Version:
 - Slimefun Version:
 - FluffyMachines Version:

**Comment by NCBPFluffyBear** [comment]
Thanks for your report, sorry that it took me some time to work on it!
