### ISSUE TITLE
Not able to loaf FluffyMachines at minecraft 1.20.6

### ISSUE THREAD

**Issue by HuJK** [NCBPFluffyBear/FluffyMachines#152]
## Description (Required)
FluffyMachines not able to load at moinecraft 1.20.6

## Steps to reproduce the Issue (Required)
Put FluffyMachines.jar into plugins and start the server

## Expected behavior (Required)
Load normally

## Server Log / Error Report
```
[17:21:37 ERROR]: Error occurred while enabling FluffyMachines vDEV - 132 (git ccf029ba) (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.enchantments.Enchantment.isAcceptingRegistrations()'
        at FluffyMachines-132.jar/io.ncbpfluffybear.fluffymachines.FluffyMachines.onEnable(FluffyMachines.java:61) ~[FluffyMachines-132.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

## Environment (Required)

 - Minecraft Version: 1.20.6
 - CS-CoreLib Version: 
 - Slimefun Version:  DEV-1104
 - FluffyMachines Version: DEV-132

## Comment
`org.bukkit.enchantments.Enchantment.isAcceptingRegistrations()` has been removed in minecraft 1.20.3, please update this plugin for it, many thanks!

**Comment by HuJK** [comment]
Oh, I have to download from new site
blob.build instead of thebusybiscuit.github.io
