### ISSUE TITLE
MINI_FLUFFY_BARREL

### ISSUE THREAD

**Issue by isaacgamemati** [NCBPFluffyBear/FluffyMachines#157]
[16:44:14 ERROR]: [FluffyMachines] Item "MINI_FLUFFY_BARREL" from FluffyMachines vDev - 8 has caused an Error!
[16:44:14 ERROR]: [FluffyMachines] You can report it here: https://github.com/NCBPFluffyBear/FluffyMachines/issues
[16:44:14 ERROR]: [FluffyMachines] An Error occurred while trying to create a BlockMenu
java.lang.ClassCastException: Cannot cast io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack to org.bukkit.craftbukkit.inventory.CraftItemStack
        at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at Slimefun-19ee76c7.jar/me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.replaceExistingItem(ChestMenu.java:252) ~[Slimefun-19ee76c7.jar:?]
        at Slimefun-19ee76c7.jar/me.mrCookieSlime.Slimefun.api.inventory.DirtyChestMenu.replaceExistingItem(DirtyChestMenu.java:169) ~[Slimefun-19ee76c7.jar:?]
        at Slimefun-19ee76c7.jar/me.mrCookieSlime.Slimefun.api.inventory.DirtyChestMenu.replaceExistingItem(DirtyChestMenu.java:160) ~[Slimefun-19ee76c7.jar:?]
        at FluffyMachines.jar/io.ncbpfluffybear.fluffymachines.items.Barrel.buildMenu(Barrel.java:272) ~[FluffyMachines.jar:?]
        at FluffyMachines.jar/io.ncbpfluffybear.fluffymachines.items.MiniBarrel.buildMenu(MiniBarrel.java:39) ~[FluffyMachines.jar:?]
        at FluffyMachines.jar/io.ncbpfluffybear.fluffymachines.items.Barrel$1.newInstance(Barrel.java:97) ~[FluffyMachines.jar:?]
        at Slimefun-19ee76c7.jar/me.mrCookieSlime.Slimefun.api.inventory.BlockMenuPreset.lambda$newInstance$0(BlockMenuPreset.java:257) ~[Slimefun-19ee76c7.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by isaacgamemati** [comment]
https://mclo.gs/rUbCR6q

**Comment by NCBPFluffyBear** [comment]
Hey there, thanks for the report.

Slimefun does not currently support 1.20.1, so FluffyMachines will break too.
