### ISSUE TITLE
Error sometimes when break a barrel

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#47]
## Description (Required)

Error sometimes when break a barrel.

## Steps to reproduce the Issue (Required)

Break a barrel.

## Expected behavior (Required)

No error when break a barrel.

## Server Log / Error Report

```
[12:19:51] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Slimefun vDEV - 767 (git 2ced45b4)
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at io.ncbpfluffybear.fluffymachines.items.Barrel.lambda$new$0(Barrel.java:146) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:159) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:124) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor958.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:357) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:310) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:245) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1494) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1203) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:125) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1271) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1011) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

## Environment (Required)

[13:19:39 INFO]: Yatopia v1_16_R3
[13:19:39 INFO]: CS-CoreLib vDEV - 92 (git e9150d72)
[13:19:39 INFO]: Slimefun vDEV - 767 (git 2ced45b4)
[13:19:39 INFO]: Metrics build: #17
[13:19:39 INFO]: 
[13:19:39 INFO]: Installed Addons: (12)
[13:19:39 INFO]:  DyedBackpacks vDEV - 11 (git b8eda0c7)
[13:19:39 INFO]:  RestrictedCreative v2.4.4
[13:19:39 INFO]:  ExtraTools vDEV - 23 (git 9299a65c)
[13:19:39 INFO]:  PomaExpansion vDEV - 10 (git 3f46213c)
[13:19:39 INFO]:  LiteXpansion vDEV - 100 (git cae4353e)
[13:19:39 INFO]:  SlimefunOreChunks vDEV - 10 (git 91df3b8e)
[13:19:39 INFO]:  HotbarPets vDEV - 32 (git 977f0591)
[13:19:39 INFO]:  EcoPower vDEV - 2 (git b0c0c875)
[13:19:39 INFO]:  ExtraGear vDEV - 12 (git 4570ea2c)
[13:19:39 INFO]:  SlimefunLuckyBlocks vDEV - 30 (git 26824119)
[13:19:39 INFO]:  FluffyMachines vDEV - 55 (git e54c1b54)
[13:19:39 INFO]:  SlimefunPomaFix v1.0-SNAPSHOT

**Comment by NCBPFluffyBear** [comment]
Are you somehow modifying the data of the barrel using commands? What kind of barrel was it? How many items were inside?

**Comment by NCBPFluffyBear** [comment]
Didn't get a reply, closing.

**Comment by andris155** [comment]
I don't know what caused this but there is no such the error anymore.
