### ISSUE TITLE
foundry gets empty suddenly and doesnt work

### ISSUE THREAD

**Issue by RIPISDRAD** [NCBPFluffyBear/FluffyMachines#86]
![2021-04-18_15 39 16](https://user-images.githubusercontent.com/76468672/115145116-45e97180-a065-11eb-875c-287f38213c1b.png)
![2021-04-18_15 39 07](https://user-images.githubusercontent.com/76468672/115145120-484bcb80-a065-11eb-92ca-21223ec526c1.png)
![2021-04-18_15 31 50](https://user-images.githubusercontent.com/76468672/115145122-4a158f00-a065-11eb-9f2e-424f02d6af98.png)
and that is lead dust in the picture 
they all were full but after sometime they get suddenly empty
2-this error happens and i dont know why
[14:44:55] [Server thread/ERROR]: [FluffyMachines] Could not pass "BlockBreakHandler" for SuperheatedFurnace - 'SUPERHEATED_FURNACE' (FluffyMachines vDEV - 77 (git c50768fa))
java.lang.NullPointerException: null
	at io.ncbpfluffybear.fluffymachines.multiblocks.components.SuperheatedFurnace$2.onPlayerBreak(SuperheatedFurnace.java:222) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callBlockHandler$2(BlockListener.java:172) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.callItemHandler(SlimefunItem.java:956) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:172) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:128) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor530.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-573]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-573]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-573]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:358) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:317) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1634) ~[?:git-Paper-573]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-573]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-573]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by NCBPFluffyBear** [comment]
I'm going to need more information to reproduce it. It seems that someone tried to break the furnace, but the "lava" (The lava texture that appears in the glass) was not there.

**Comment by NCBPFluffyBear** [comment]
I have fixed the code and added a check to make sure this error doesn't happen again, but this shouldn't have happened in the first place unless the armor stand was tampered with.

**Comment by RIPISDRAD** [comment]
plz tell me what information do u need?
how i can get them!
and they might just move and replace the pieces too
btw they report it that they have lost all of their storage at once

**Comment by NCBPFluffyBear** [comment]
That error message you sent is only possible if they tried to break the foundry. The foundry should not spontaneously lose items. I can't provide you exact steps to show me the issue, since I don't know the issue in the first place. If there are any other error messages, let me know.

**Comment by RIPISDRAD** [comment]
It happened once before (i cant provide any info from this)
But in the nearest report as u see they were actually true they stopped
working for some reason and didn't fill their inventori
They just suddenly stopeed working like there is nothing to be stored and i
checked they got sth wrong and got no idea how they got cleared they're own
inventory
I can show u my server and whatever u need but there is nothing else but
play like 10 days straight
They litrally builed a sf dust farm (cobble generator+cobble become
gravel+gravel goes to electric dust farm+input and output cargoes and chest
and foundry and that's all (all is automatic)

**Comment by RIPISDRAD** [comment]
Btw it happens 2days ago from that version 2days ago from the time i
reported it like 7 or 8 days ago from now and thats all

**Comment by NCBPFluffyBear** [comment]
If you updated to the latest version, there is no way you got the exact same error in console. Send me the new error. Also next time please reply in both english and your native language, I can't really understand you.

**Comment by RIPISDRAD** [comment]
I will try to speak more clearly tnx for ur help if sth new came up i will
post it

**Comment by NCBPFluffyBear** [comment]
Closing due to no response for over a week. Feel free to open if this issue occurs again.
